### ISSUE TITLE
angular-fullstack:endpoint not working

### ISSUE THREAD

**Issue by pasupulaphani** [angular-fullstack/generator-angular-fullstack#1085]
~/new_work/startjoin $ yo angular-fullstack:endpoint project
? What will the url of your endpoint be? /api/projects

```
/Users/phani/.nvm/versions/node/v0.12.3/lib/node_modules/generator-angular-fullstack/endpoint/index.js:58
  if (this.filters.socketio) {
                  ^
TypeError: Cannot read property 'socketio' of undefined
    at Generator.registerEndpoint (/Users/phani/.nvm/versions/node/v0.12.3/lib/node_modules/generator-angular-fullstack/endpoint/index.js:58:19)
    at /Users/phani/.nvm/versions/node/v0.12.3/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by kingcody** [comment]
Do you know what version of the generator you used when you initial created your project? Also what version of the generator did you use to generate the endpoint?

**Comment by pasupulaphani** [comment]
$ npm angular-fullstack -v
    2.9.1

**Comment by kingcody** [comment]
What is the contents of your `.yo-rc.json` file?

**Comment by Awk34** [comment]
@pasupulaphani that's your NPM version. To get the version of your installed generator, run `npm list -g generator-angular-fullstack`.

**Comment by pasupulaphani** [comment]
sorry here is the version

$ npm list -g generator-angular-fullstack
/Users/phani/.nvm/versions/node/v0.12.3/lib
└── generator-angular-fullstack@2.1.0

**Comment by kingcody** [comment]
@pasupulaphani
Are you still experiencing this issue? If so:
> What are the contents of your .yo-rc.json file?

**Comment by stodd** [comment]
I'm having the same issue.

generator version:
```
    generator-angular-fullstack@2.0.13
```
.yo-rc.json:
```
{
  "generator-angular-fullstack": {
    "insertRoutes": true,
    "registerRoutesFile": "server/routes.js",
    "routesNeedle": "// Insert routes below",
    "routesBase": "/api/",
    "pluralizeRoutes": true,
    "insertSockets": true,
    "registerSocketsFile": "server/config/socketio.js",
    "socketsNeedle": "// Insert sockets below",
    "filters": {
      "coffee": true,
      "html": true,
      "sass": true,
      "ngroute": true,
      "bootstrap": true,
      "uibootstrap": true,
      "socketio": true,
      "mongoose": true,
      "auth": true,
      "oauth": true,
      "googleAuth": true,
      "facebookAuth": true,
      "twitterAuth": true
    }
  },
  "generator-ng-component": {
    "routeDirectory": "client/app/",
    "directiveDirectory": "client/app/",
    "filterDirectory": "client/app/",
    "serviceDirectory": "client/app/",
    "basePath": "client",
    "moduleName": "",
    "filters": [
      "ngroute"
    ],
    "extensions": [
      "coffee",
      "html",
      "scss"
    ],
    "directiveSimpleTemplates": "",
    "directiveComplexTemplates": "",
    "filterTemplates": "",
    "serviceTemplates": "",
    "factoryTemplates": "",
    "controllerTemplates": "",
    "decoratorTemplates": "",
    "providerTemplates": "",
    "routeTemplates": ""
  }
}
```

**Comment by stodd** [comment]
Resolved
Well that is embarrassing. To anyone getting this error dbl check the directory you are in.

**Comment by trentjones21** [comment]
I am still having this issue, and I am in the correct directory as far as I know.

**Comment by Awk34** [comment]
@trentjones21 you're running the command from the root of your project directory, correct?

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by abinthomasonline** [comment]
I too have this issue...
I'm running the command from the root of my project directory..
