### ISSUE TITLE
@4.0.1 stable release after npm install gulp serve not starting server, on windows 

### ISSUE THREAD

**Issue by dhruvaprajapati** [angular-fullstack/generator-angular-fullstack#2166]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

Log 

  41:2   error  Unnecessary semicolon                    no-extra-semi

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\modal\modal.service.js
  13:5   error    'angular' is not defined                                         no-undef
  33:20  error    'angular' is not defined                                         no-undef
  40:11  error    Split 'var' declarations into multiple statements                one-var
  40:22  warning  Avoid using Function.prototype.call, instead use Reflect.apply   prefer-reflect
  40:49  warning  Use the rest parameters instead of 'arguments'                   prefer-rest-params
  48:21  warning  Unexpected string concatenation                                  prefer-template
  52:17  warning  Expected method shorthand                                        object-shorthand
  58:17  warning  Expected method shorthand                                        object-shorthand
  66:13  warning  Avoid using Function.prototype.apply, instead use Reflect.apply  prefer-reflect
  74:16  error    'angular' is not defined                                         no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\navbar\navbar.component.js
   5:5   error    Unnecessarily quoted property 'title' found   quote-props
   6:5   error    Unnecessarily quoted property 'state' found   quote-props
  16:23  warning  Unexpected sync method: 'isLoggedInSync'      no-sync
  17:20  warning  Unexpected sync method: 'isAdminSync'         no-sync
  18:27  warning  Unexpected sync method: 'getCurrentUserSync'  no-sync
  23:16  error    'angular' is not defined                      no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\mongoose-error\mongoose-error.directive.js
   7:1  error    'angular' is not defined   no-undef
  12:7  warning  Expected method shorthand  object-shorthand

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\oauth-buttons\index.js
  5:29  warning  Unexpected string concatenation  prefer-template
  9:16  error    'angular' is not defined         no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\socket\socket.service.js
  31:18  error    'angular' is not defined         no-undef
  36:17  warning  Unexpected string concatenation  prefer-template
  37:23  error    '_' is not defined               no-undef
  45:9   error    Unexpected space(s) after "if"   keyword-spacing
  58:17  warning  Unexpected string concatenation  prefer-template
  60:9   error    '_' is not defined               no-undef
  73:33  warning  Unexpected string concatenation  prefer-template
  74:33  warning  Unexpected string concatenation  prefer-template
  79:16  error    'angular' is not defined         no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\util\util.module.js
  7:16  error  'angular' is not defined  no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\components\util\util.service.js
  18:14  error    'angular' is not defined                             no-undef
  18:44  error    'angular' is not defined                             no-undef
  32:7   error    Unexpected space(s) after "if"                       keyword-spacing
  58:99  warning  '===' should be placed at the beginning of the line  operator-linebreak

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\login\index.js
  5:16  error  'angular' is not defined  no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\login\login.controller.js
  32:5   error  Unexpected space(s) after "if"                           keyword-spacing
  34:11  error  Expected indentation of 8 space characters but found 10  indent
  35:11  error  Expected indentation of 8 space characters but found 10  indent
  36:9   error  Expected indentation of 6 space characters but found 8   indent

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\settings\index.js
  5:16  error  'angular' is not defined  no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\settings\settings.controller.js
  31:5  error  Unexpected space(s) after "if"  keyword-spacing

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\signup\index.js
  5:16  error  'angular' is not defined  no-undef

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\client\app\account\signup\signup.controller.js
  30:5   error  Unexpected space(s) after "if"                           keyword-spacing
  32:11  error  Expected indentation of 8 space characters but found 10  indent
  33:11  error  Expected indentation of 8 space characters but found 10  indent
  34:11  error  Expected indentation of 8 space characters but found 10  indent
  35:9   error  Expected indentation of 6 space characters but found 8   indent
  44:11  error  'angular' is not defined                                 no-undef

✖ 94 problems (70 errors, 24 warnings)

[18:44:08] Finished 'lint:scripts:client' after 3.58 s
[18:44:08] Finished 'copy:fonts:dev' after 3.59 s
[18:44:09]
C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\app.js
  16:17  warning  Unexpected string concatenation
         prefer-template
  17:3   error    Don't use process.exit(); throw an error instead
         no-process-exit
  21:1   error    Unexpected space(s) after "if"
         keyword-spacing
  21:22  error    Statement inside of curly braces should be on next line
         brace-style
  21:22  error    Closing curly brace should be on the same line as opening curly brace or on the line after the previou
s block  brace-style

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\index.js
  4:11  warning  Unexpected use of process.env   no-process-env
  4:34  warning  Unexpected use of process.env   no-process-env
  6:1   error    Unexpected space(s) after "if"  keyword-spacing

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\routes.js
  24:33  warning  Unexpected string concatenation  prefer-template

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\auth\auth.service.js
   3:8   error    'passport' is defined but never used                    no-unused-vars
  23:7   error    Unexpected space(s) after "if"                          keyword-spacing
  24:37  warning  Unexpected string concatenation                         prefer-template
  27:6   error    Unexpected space(s) after "if"                          keyword-spacing
  27:6   error    Expected indentation of 6 space characters but found 5  indent
  28:36  warning  Unexpected string concatenation                         prefer-template
  36:11  error    Unexpected space(s) after "if"                          keyword-spacing
  50:3   error    Unexpected space(s) after "if"                          keyword-spacing
  57:7   error    Unexpected space(s) after "if"                          keyword-spacing
  57:53  warning  '>=' should be placed at the beginning of the line      operator-linebreak
  59:9   error    Expected return with your callback function             callback-return
  70:30  warning  Expected property shorthand                             object-shorthand
  79:3   error    Unexpected space(s) after "if"                          keyword-spacing

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\auth\index.js
  4:8  error  'passport' is defined but never used  no-unused-vars

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\config\express.js
   27:3   error    Unexpected space(s) after "if"                            keyword-spacing
   31:3   error    Unexpected space(s) after "if"                            keyword-spacing
   39:20  warning  Unexpected string concatenation                           prefer-template
   48:1   error    Trailing spaces not allowed                               no-trailing-spaces
   66:3   error    Unexpected space(s) after "if"                            keyword-spacing
   66:26  warning  Unexpected use of process.env                             no-process-env
   81:3   error    Unexpected space(s) after "if"                            keyword-spacing
   81:7   error    Expected literal to be on the right side of ===           yoda
   83:45  error    Trailing spaces not allowed                               no-trailing-spaces
   88:58  error    Trailing spaces not allowed                               no-trailing-spaces
   96:14  warning  Unexpected string concatenation                           prefer-template
  104:26  error    Trailing spaces not allowed                               no-trailing-spaces
  116:37  error    Unexpected space before function parentheses              space-before-function-paren
  118:9   error    Expected indentation of 6 space characters but found 8    indent
  118:9   error    Unexpected space(s) after "if"                            keyword-spacing
  119:13  error    Expected indentation of 10 space characters but found 12  indent
  120:17  error    Expected indentation of 14 space characters but found 16  indent
  120:24  error    Strings must use singlequote                              quotes
  121:17  error    Expected indentation of 14 space characters but found 16  indent
  122:17  error    Expected indentation of 14 space characters but found 16  indent
  125:9   error    Expected indentation of 6 space characters but found 8    indent
  129:3   error    Unexpected space(s) after "if"                            keyword-spacing
  129:7   error    Expected literal to be on the right side of ===           yoda
  129:32  error    Expected literal to be on the right side of ===           yoda

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\config\seed.js
  14:97  warning  '+' should be placed at the beginning of the line  operator-linebreak
  15:78  warning  '+' should be placed at the beginning of the line  operator-linebreak
  19:72  warning  '+' should be placed at the beginning of the line  operator-linebreak
  23:73  warning  '+' should be placed at the beginning of the line  operator-linebreak
  24:75  warning  '+' should be placed at the beginning of the line  operator-linebreak
  28:75  warning  '+' should be placed at the beginning of the line  operator-linebreak
  32:78  warning  '+' should be placed at the beginning of the line  operator-linebreak
  33:80  warning  '+' should be placed at the beginning of the line  operator-linebreak
  37:79  warning  '+' should be placed at the beginning of the line  operator-linebreak

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\config\socketio.js
   6:8   error    'config' is defined but never used                 no-unused-vars
   9:23  error    'socket' is defined but never used                 no-unused-vars
  22:1   error    Block must not be padded by blank lines            padded-blocks
  41:22  warning  Unexpected string concatenation                    prefer-template
  41:63  warning  '+' should be placed at the beginning of the line  operator-linebreak

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\api\thing\thing.controller.js
   29:7  warning  Avoid using Function.prototype.apply, instead use Reflect.apply     prefer-reflect
   91:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect
  102:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\api\thing\thing.events.js
  28:22  warning  Unexpected string concatenation  prefer-template

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\api\user\user.controller.js
    4:8   error  'passport' is defined but never used  no-unused-vars
   12:4   error  Missing semicolon                     semi
   37:34  error  'next' is defined but never used      no-unused-vars
   59:7   error  Unexpected space(s) after "if"        keyword-spacing
   82:42  error  'next' is defined but never used      no-unused-vars
   89:7   error  Unexpected space(s) after "if"        keyword-spacing
  110:7   error  Unexpected space(s) after "if"        keyword-spacing
  121:40  error  'next' is defined but never used      no-unused-vars

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\api\user\user.events.js
  16:3   error    Unnecessarily quoted property 'save' found      quote-props
  17:3   error    Unnecessarily quoted property 'remove' found    quote-props
  21:1   error    Unexpected space(s) after "for"                 keyword-spacing
  26:20  error    'event' is already declared in the upper scope  no-shadow
  28:21  warning  Unexpected string concatenation                 prefer-template
  30:4   error    Missing semicolon                               semi

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server\api\user\user.model.js
   28:5   warning  Expected method shorthand                       object-shorthand
  194:15  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  195:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  197:22  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  198:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  238:14  warning  Unexpected sync method: 'pbkdf2Sync'            no-sync
  244:9   error    Expected return with your callback function     callback-return
  246:9   error    Expected return with your callback function     callback-return

✖ 87 problems (54 errors, 33 warnings)

[18:44:09] Finished 'lint:scripts:server' after 3.69 s
[18:44:09] Finished 'lint:scripts' after 3.72 s
[18:44:09] Starting 'start:server'...
[18:44:09] Finished 'start:server' after 14 ms
[18:44:09] Starting 'start:client'...
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\server/**/*
[nodemon] starting `node server`
module.js:442
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (express.js:10:1)
    at Module._compile (module.js:541:32)
    at loader (C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\node_modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\
node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (app.js:31:1)
    at Module._compile (module.js:541:32)
    at loader (C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\node_modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\
node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
 [nodemon] app crashed - waiting for file changes before starting...
^CTerminate batch job (Y/N)? y

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm>npm install shrink-ray

> iltorb@1.0.12 install C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\node_modules\iltorb
> node-gyp rebuild

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:
\Users\Dhruv\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
 )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Dhruv\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\config
ure.js:449:14)
gyp ERR! stack     at C:\Users\Dhruv\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dhruv\\AppData\\Roaming\\npm\\node_modules\\npm\\node
_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\node_modules\iltorb
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
icrm@0.0.0 C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm
`-- (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /stylint/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dhruv\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\np
m-cli.js" "install" "shrink-ray"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm\npm-debug.log
npm ERR! code 1

C:\Users\Dhruv\projects\github.com\dhruvaprajapati\icrm>

**Comment by Koslun** [comment]
Please edit your post with the exact choices you made, your npm, node and os version. I.e. edit the two tables at the top of your answer.

Is it a problem with installing `npm-gyp`? As stated in the readme, it's a requirement to the project.

**Comment by GameHex** [comment]
Run `npm i -g npm`. There's a problem with one of the not newest npm versions not doing node-gyp correctly for shrink-ray. I just fixed it by updating npm, deleting the entire node_modules folder contents, then running npm install again. Good luck!

**Comment by michaeljota** [comment]
@GameHex Thanks! This solves the problem to me. 

PS: The team should update readme asking to use the last npm version (3.10.7)

**Comment by stockman** [comment]
This problem still persists in version 4.1.4.  
shrink-ray resolution for windows:  
#https://github.com/angular-fullstack/generator-angular-fullstack/issues/2462#issuecomment-275112118

**Comment by stockman** [comment]
Would be great if the generator shipped with sqlite3 db, when selecting SQL variations so the thing would actually start up on a fresh install.
