### ISSUE TITLE
Angular-fullstack 5.0.0-rc.3 route subgenerator does not work

### ISSUE THREAD

**Issue by soccer-coder** [angular-fullstack/generator-angular-fullstack#2743]
- [x ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.3
Node | 8.11.2
npm | 6.1.0
Operating System | MacOs

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS / Stylus
Router | ngRoute 
DB | MongoDB 

I tried to generate the "route" as below, I ran into an issue:

yo angular-fullstack:route sidenav
? Where would you like to create this route? client/app/
? What will the url of your route be? sidenav
events.js:183
throw er; // Unhandled 'error' event
^

TypeError: Cannot read property 'name' of undefined

I could run "endpoint" without any issue.

**Comment by Awk34** [comment]
This was a bug in https://github.com/angular-fullstack/generator-angular-fullstack-component. See https://github.com/angular-fullstack/generator-angular-fullstack-component/commit/b854fdaef805f532e13056b368ed3493c65c5425. This fix was released in 1.0.2. You should be able to reinstall the generator's dependencies or the generator itself for it to get the fixed version.

**Comment by fcristel** [comment]
Is this still not working? I am running on Windows, on a freshly installed version of the generator (yesterday). 

First of all, the generator comes with generator-angular-fullstack-component 1.0.1

And I get this error:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
```


If I update the generator-angular-fullstack-component to the 1.0.2, then the error is this one:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'generator-angular-fullstack-component/generators/route'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at RouteGenerator.compose (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\generators\route\index.js:13:30)
    at Object.<anonymous> (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by pschoro** [comment]
Hey guys,

The issue is still there on the route generator: 

? Where would you like to create this route? client/app/
? What will the url of your route be? dashboard
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined

**Comment by Awk34** [comment]
@pschoro would you be willing to make a pull request?

**Comment by pschoro** [comment]
No need ...it was simply a typo in the variable _jscodeshift...I did not change anything else ^^
